SRCDIR=$(dir $(shell pwd)/../../)
INSTALL_DIR=./usr
KCONFIG_CONFIG?=config
VPATH=$(SRCDIR)
KERNEL_DIR=
#KERNEL_DIR=freebsd5
KERNEL_VERSION=192c73782cbd4de31a183a4a6021f195e180d1fb

CONFIG_CFLAGS+= \
 $(opt_$(OPT)) -g3 -Wall \
 -I$(SRCDIR)$(KERNEL_DIR)/lib/libjail \
 -I$(SRCDIR)$(KERNEL_DIR)/include \
 -I$(SRCDIR)$(KERNEL_DIR)/sys \
 -I$(SRCDIR)$(KERNEL_DIR)/sys/sys \
 -I$(SRCDIR)/$(KERNEL_DIR) \
 -I$(SRCDIR)$(KERNEL_DIR)/sys/sim \
 -I$(SRCDIR)/$(KERNEL_DIR)/sys/contrib/altq/ \
 -I$(SRCDIR)/$(KERNEL_DIR)/sys/contrib/pf/ \
 -D__srget=getc -D__swbuf=putc \
 -D__FreeBSD__=5  -D_VA_LIST_DEFINED \
 -D__stdinp=stdin -D__stderrp=stderr -D__stdoutp=stdout \
 -D__builtin_stdarg_start=__builtin_va_start \
 -ffreestanding -std=gnu99 -Dlint

YACC=yacc -d

all: config

%.o:%.c
	$(CC) $(CONFIG_CFLAGS) -c $^ -o $@

# For FreeBSD config build
CONFIG_DIR=$(SRCDIR)/usr.sbin/config
CONFIG_SRC=config.y main.c lang.l mkmakefile.c mkheaders.c \
        mkoptions.c subr_sbuf.c
CONFIG_OBJ=$(addprefix $(CONFIG_DIR)/,$(addsuffix .o,$(basename $(CONFIG_SRC))))
HEADER=$(CONFIG_DIR)/y.tab.h

$(CONFIG_DIR)/subr_sbuf.c:
	echo "SRCDIR= " $(SRCDIR)
	echo "MAKEFILE_LIST = " $(MAKEFILE_LIST)
	/bin/cp $(SRCDIR)/sys/kern/subr_sbuf.c $(CONFIG_DIR)

$(HEADER): $(CONFIG_DIR)/config.c
	mv -f y.tab.h $(CONFIG_DIR)
config: Makefile $(CONFIG_DIR)/subr_sbuf.c $(HEADER) $(CONFIG_OBJ)
	$(CC) $(LDFLAGS) $(CONFIG_OBJ) -o $@

IFCONFIG_DIR=freebsd.git/sbin/ifconfig
IFCONFIG_SRC=af_atalk.c af_inet6.c af_inet.c \
     af_nd6.c ifclone.c ifconfig.c iffib.c ifgif.c \
     ifgre.c iflagg.c ifmedia.c ifpfsync.c \
     ifvlan.c
IFCONFIG_OBJ=$(addprefix $(IFCONFIG_DIR)/,$(addsuffix .o,$(basename $(IFCONFIG_SRC))))
ifconfig: Makefile $(IFCONFIG_OBJ)
	$(CC) $(LDFLAGS) /usr/lib/libc.so $(IFCONFIG_OBJ) -o $@


clean:
	@rm -f $(CONFIG_OBJ) $(CONFIG_DIR)/config.c $(CONFIG_DIR)/y.tab.h ./config
	@rm -f $(IFCONFIG_OBJ) ./ifconfig

.PHONY : clean